{
 "title": "F2B map",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Number of banned IPs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "banned_ips_db",
     "rawSql": "SELECT COUNT(ip) FROM banned_ips_db.banned_ips LIMIT 50 "
    }
   ]
  },
  {
   "title": "Banned IPs",
   "type": "table",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "banned_ips_db",
     "rawSql": "SELECT ip, country, region, isp FROM banned_ips_db.banned_ips"
    }
   ]
  },
  {
   "title": "Banned IPs locations",
   "type": "geomap",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "dataset": "banned_ips_db",
     "rawSql": "SELECT latitude, longitude, ip, country, region, isp FROM banned_ips_db.banned_ips"
    }
   ]
  }
 ]
}