
services:
  mysql:
    image: mysql:5.7
    container_name: mysql-f2b-geo-export
    environment:
      MYSQL_ROOT_PASSWORD: _sqlrootpassword_
      TZ: "Europe/Zurich"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./app/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    expose:
      - 3306
    networks:
      - net_prometheus
      - net_f2b_geo_export
    restart: always

  f2b-geo-exporter:
    build: .
    container_name: f2b-geo-exporter
    depends_on:
      - mysql
    volumes:
      - /var/log/fail2ban.log:/var/log/fail2ban.log
      #- ./app/f2b-geo-parser.py:/dev/f2b-geo-parser.py # More convenient for developping, keep commented otherwise
    environment:
      MYSQL_HOST: mysql-f2b-geo-export
      MYSQL_DATABASE: banned_ips_db
      MYSQL_USER: root
      MYSQL_PASSWORD: _sqlrootpassword_
      TZ: "UTC" # It's good pratice to store UTC timestamps in databases, keep it UTC and Grafana will do the rest
      EXPORT_INTERVAL: 5 # Interval in minutes for the exporter to run
      RETENTION_DAYS: 30 # Remove entries older than 30 days
    networks:
      - net_f2b_geo_export
    restart: always

volumes:
  mysql_data:

networks:
  net_f2b_geo_export:
    name: net_f2b_geo_export
  net_prometheus:
    external: true