{
 "title": "F2B map",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Number of banned IPs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "banned_ips_db",
     "rawSql": "SELECT COUNT(ip) FROM banned_ips_db.banned_ips LIMIT 50 "
    }
   ]
  },
  {
   "title": "Total failed attempts",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "banned_ips_db",
     "rawSql": "SELECT SUM(attempts) FROM banned_ips_db.banned_ips LIMIT 50 "
    }
   ]
  },
  {
   "title": "Number of bans over time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "banned_ips_db",
     "rawSql": "SELECT timestamp, num FROM banned_ips_db.num_bans LIMIT 50 "
    }
   ]
  },
  {
   "title": "Banned IPs locations",
   "type": "geomap",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "dataset": "banned_ips_db",
     "rawSql": "SELECT latitude, longitude, ip, country, city, isp FROM banned_ips_db.banned_ips"
    }
   ]
  },
  {
   "title": "By countries",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "dataset": "banned_ips_db",
     "rawSql": "SELECT country FROM banned_ips_db.banned_ips LIMIT 50 "
    }
   ]
  },
  {
   "title": "Banned IPs",
   "type": "table",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "dataset": "banned_ips_db",
     "rawSql": "SELECT bantime, ip, attempts, country, city, isp FROM banned_ips_db.banned_ips ORDER BY bantime"
    }
   ]
  }
 ]
}